### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Sergey-Rozhkov** [dtsaryov/ha-get-ppl-repos#1]
```
$ node gpr.js ecmascript-15 /home/orange/Projects/html-a/js2-15
Cloning https://github.com/htmlacademy-ecmascript/1275829-big-trip-15.git...
(node:22353) UnhandledPromiseRejectionWarning: TypeError: repo.description.replaceAll is not a function
    at getRepoTargetDir (/home/orange/Projects/html-a/ha-get-ppl-repos/src/git.js:4:40)
    at /home/orange/Projects/html-a/ha-get-ppl-repos/src/git.js:13:34
    at Array.forEach (<anonymous>)
    at clone (/home/orange/Projects/html-a/ha-get-ppl-repos/src/git.js:11:9)
    at /home/orange/Projects/html-a/ha-get-ppl-repos/src/main.js:13:7
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22353) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Всё сделал по инструкции, но не работает

**Comment by dtsaryov** [comment]
@Sergey-Rozhkov привет, спасибо за ишью

Можешь показать, что выведет `console.log(repo)` внутри функции `git.js/getRepoTargetDir` ?

Возможно, недостаточно только `repo` группы для токена

**Comment by Sergey-Rozhkov** [comment]
``` {
  id: 390035307,
  node_id: 'MDEwOlJlcG9zaXRvcnkzOTAwMzUzMDc=',
  name: '1275829-big-trip-15',
  full_name: 'htmlacademy-ecmascript/1275829-big-trip-15',
  private: false,
  owner: {
    login: 'htmlacademy-ecmascript',
    id: 22890904,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjIyODkwOTA0',
    avatar_url: 'https://avatars.githubusercontent.com/u/22890904?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/htmlacademy-ecmascript',
    html_url: 'https://github.com/htmlacademy-ecmascript',
    followers_url: 'https://api.github.com/users/htmlacademy-ecmascript/followers',
    following_url: 'https://api.github.com/users/htmlacademy-ecmascript/following{/other_user}',
    gists_url: 'https://api.github.com/users/htmlacademy-ecmascript/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/htmlacademy-ecmascript/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/htmlacademy-ecmascript/subscriptions',
    organizations_url: 'https://api.github.com/users/htmlacademy-ecmascript/orgs',
    repos_url: 'https://api.github.com/users/htmlacademy-ecmascript/repos',
    events_url: 'https://api.github.com/users/htmlacademy-ecmascript/events{/privacy}',
    received_events_url: 'https://api.github.com/users/htmlacademy-ecmascript/received_events',
    type: 'Organization',
    site_admin: false
  },
  html_url: 'https://github.com/htmlacademy-ecmascript/1275829-big-trip-15',
  description: 'Татьяна Минина',
  fork: false,
  url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15',
  forks_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/forks',
  keys_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/keys{/key_id}',
  collaborators_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/collaborators{/collaborator}',
  teams_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/teams',
  hooks_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/hooks',
  issue_events_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/issues/events{/number}',
  events_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/events',
  assignees_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/assignees{/user}',
  branches_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/branches{/branch}',
  tags_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/tags',
  blobs_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/git/blobs{/sha}',
  git_tags_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/git/tags{/sha}',
  git_refs_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/git/refs{/sha}',
  trees_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/git/trees{/sha}',
  statuses_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/statuses/{sha}',
  languages_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/languages',
  stargazers_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/stargazers',
  contributors_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/contributors',
  subscribers_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/subscribers',
  subscription_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/subscription',
  commits_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/commits{/sha}',
  git_commits_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/git/commits{/sha}',
  comments_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/comments{/number}',
  issue_comment_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/issues/comments{/number}',
  contents_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/contents/{+path}',
  compare_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/compare/{base}...{head}',
  merges_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/merges',
  archive_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/{archive_format}{/ref}',
  downloads_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/downloads',
  issues_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/issues{/number}',
  pulls_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/pulls{/number}',
  milestones_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/milestones{/number}',
  notifications_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/notifications{?since,all,participating}',
  labels_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/labels{/name}',
  releases_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/releases{/id}',
  deployments_url: 'https://api.github.com/repos/htmlacademy-ecmascript/1275829-big-trip-15/deployments',
  created_at: '2021-07-27T15:30:28Z',
  updated_at: '2021-08-30T06:12:40Z',
  pushed_at: '2021-09-02T06:01:22Z',
  git_url: 'git://github.com/htmlacademy-ecmascript/1275829-big-trip-15.git',
  ssh_url: 'git@github.com:htmlacademy-ecmascript/1275829-big-trip-15.git',
  clone_url: 'https://github.com/htmlacademy-ecmascript/1275829-big-trip-15.git',
  svn_url: 'https://github.com/htmlacademy-ecmascript/1275829-big-trip-15',
  homepage: 'https://github.com/nastradalus/1275829-big-trip-15',
  size: 452,
  stargazers_count: 0,
  watchers_count: 0,
  language: 'HTML',
  has_issues: false,
  has_projects: true,
  has_downloads: false,
  has_wiki: false,
  has_pages: false,
  forks_count: 1,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 1,
  license: null,
  forks: 1,
  open_issues: 1,
  watchers: 0,
  default_branch: 'master',
  permissions: { admin: true, maintain: true, push: true, triage: true, pull: true }
}
```

**Comment by Sergey-Rozhkov** [comment]
```
$ node -v
v14.17.6
$ npm -v
6.14.15
```

replaceAll судя по всему не доехал до меня
Ubuntu 20.04.3 LTS

> String.prototype.replaceAll() is now a valid function in JS but has no support in Node yet

**Comment by Sergey-Rozhkov** [comment]
![image](https://user-images.githubusercontent.com/1179947/132003996-60be8ad1-2055-469c-abe6-4aa6d5b8ccf7.png)

вот так всё сработало

**Comment by dtsaryov** [comment]
Да, дело действительно в версии ноды. Я использовал 16ю.

Чуть позже добавлю требования и, пожалуй, поддержку LTS версии

**Comment by Sergey-Rozhkov** [comment]
просто замени `replaceAll` на `replace` как на скрине, и не нужно ни каких требований
